### ISSUE TITLE
Cc messages ?

### ISSUE THREAD

**Issue by daslicht** [maxmechanic/xbox-midi-controller#1]
Hi, 
Is it possible to send midi cc messages by with the sticks ?
~Marc

**Comment by maxmechanic** [comment]
The library is not currently set up to do that, but the [underlying node interface](https://github.com/andrew/node-xbox-controller) would support it.

What sort of cc messages would you want the sticks to send?

**Comment by daslicht** [comment]
it would be awesome to be able to automate the cutoff etc of a synth plugin. Or even XY pad things.
Or what do you mean by type ?

**Comment by maxmechanic** [comment]
I was mostly soliciting examples of what sort of functionality you had in mind.

I have some ideas for how to set up the sticks so you can pass in a callback that'll receive the stick position and the midi output (so you as a lib user can dictate what you want to do on what position), but I may not have time for a few days to sketch it.

**Comment by daslicht** [comment]
No worries , it was just n idea of usage but it has no priority.
